### ISSUE TITLE
Undefined mixin 'respond-to

### ISSUE THREAD

**Issue by mfd** [marcoscv-work/Liferay-6.2-with-Bootstrap-3.x-theme#1]
where are stay mixin respond-to??

**Comment by justLuiz** [comment]
U can change this line to 

`@extend .visible-md-block;`

**Comment by marcoscv-work** [comment]
Wow! sorry guys, I didn't see this issue.

Try with that extend, and let us know, thanks!

**Comment by marcoscv-work** [comment]
@mfd which SDK are you using to compile the theme?

**Comment by justLuiz** [comment]
well, my previous suggestion will not solve the problem, since there are other calls to this mixins. This mixin is not from the boostrap, it is implemented by liferay, if you are using liferay-template-tasks, make sure `sassOptions.IncludePaths` is not overwriting the liferay files.
https://github.com/liferay/liferay-theme-tasks/issues/35

**Comment by marcoscv-work** [comment]
yes, of course, you will need this mixins:
https://github.com/marcoscv-work/Liferay-6.2-with-Bootstrap-3.x-theme/blob/master/src/css/aui/bs3/_bs2_extender.scss#L3

Be sure you are surrounded by a Liferay oficial SDK
